### ISSUE TITLE
Copying the library with Gradle

### ISSUE THREAD

**Issue by mseleng** [Ginever/JFreeType2#1]
Hi, I guess, you probably are not developing this library anymore, but I need to use FreeType in my project and I just came along it, and I guess, it is awesome (at least I was not able to find any lightweight library that would actually work until now). So I am trying to set it up, as suggested, I have a Gradle project, but I can't figure what do you mean by setting the `java.library.path` step. I thought that when Gradle downloads those dependencies, they are automatically on the classpath, so how is it?
I can't find those files anywhere in by build folder, and I also am quite new to gradle. Could you advice me please?

**Comment by Tinytimrob** [comment]
Hi

I work in a video game dev team and unfortunately I only worked on this library until the functions of FreeType were ported that were required to get our game to run. The team's resources are stretched extremely thin at the moment so I am not really able to spare time to work on it any more than we needed. For this reason the library is very bare-bones and a lot of FreeType functionality is not working. You will find the same issue with my FMOD 5 port ;)

If you think enough is working for you, then yes, if you want to use it you will need to set up `java.library.path` in Gradle. The reason for this is because FreeType2 is not a Java library. It is written in C/C++ and comes in the form of DLL file, DYLIB file or SO file depending on platform. While the JFreeType2 does come with some code written in Java, it is simply a JNI wrapper, so it still requires the original DLL/DYLIB/SO file for FreeType to be present in order to work. Gradle will not automatically download or extract these and Java will not automatically know where to look for them if it is asked to load them, so you have to solve both of these problems.

For the first problem (getting Gradle to download and extract them), I have packaged the respective DLL/DYLIB/SO file for each platform into its own artifact (with a `natives-X` classifier, where `X` is one of `win32`, `win64`, `osx`, `linux32`, `linux64` and `ios`). You will have to add the artifact relevant for your platform to your Gradle project and then extract its contents to a folder somewhere on your hard drive. (For example, on Windows 64 bit, add this dependency: `compile 'com.tinytimrob:jfreetype2-platform:0.1:natives-win64'`.) Note that `ios` platform is supported only in version 0.1.1-SNAPSHOT and not version 0.1.

For the second problem (where Java should look for them), this is solved by Java system property `java.library.path`, which indicates to Java the folder path(s) to look in for external DLL/DYLIB/SO files when they try to be loaded by Java code. You must set that property at project runtime to point to the subfolder containing the DLL/DYLIB/SO files you extracted.

Unfortunately, I am assuming you want an example for the `build.gradle` file on how to pull this off, but I only ever implemented this as part of a Gradle plugin. (This is a more complicated way of using Gradle where you can extend it directly with custom behaviour written in Java code)

You can see how I did that in this gist here: https://gist.github.com/Tinytimrob/76dc4118cba4e39b52236f3fc71c9057

This example is somewhat out of date, and I've simplified to only include the plugin code relevant to you, so you may have to make some modifications to get it to work.

It's also very likely there is a simpler way of doing this with only `build.gradle` file. I never explored that situation, because I had to write a custom plugin for a bunch of other reasons besides just this.

**Comment by mseleng** [comment]
Hi, thank you very much for the quick response!
Fortunately, I managed to make it load everything as needed. I manually copied the native libraries into the resources folder so I can have them on classpath directly after build and I set the `java.library.path` to that directory accordingly.

However, the problem I am facing now is that I can't load any glyph, usings `Face.loadGlyph()` method. I have no idea of what went wrong. Moreover, the method returns `"OK"` so I'd presume that everything worked fine, but when I check the `Face` for the glyph, it is `null`. 

I am desperate 😄. I am doing just a small school project for my openGL class and I just wanted to render some GUI (simple text). This is going to be fun 😄 . By any chance, don't you have an idea why it behaves like that? I already tried some bigger wrapper around `FreeType`, but I think that eventually I got the same problem. Maybe it is the font file itself. 

Anyway, I really like work you had done with this library! It is lightweight, yet still offers everything I need!

**Comment by Tinytimrob** [comment]
If Face.loadGlyph is returning OK then it should work

I'm using the library like this and it works:

```
	if (face.loadGlyph(0, FreeTypeLoadFlags.DEFAULT) != FreeTypeError.OK)
	{
		throw new Exception(error.description);
	}

	FreeTypeGlyphSlot glyph = face.getGlyph();
	if (glyph.render(FreeTypeRenderMode.NORMAL) != FreeTypeError.OK)
	{
		throw new Exception(error.description);
	}

	FreeTypeBitmap bitmap = glyph.getBitmap();
	int height = (int) bitmap.getRows();
	int width = (int) bitmap.getWidth();
	byte[] buffer = bitmap.getBuffer();
	int[] bufferi = new int[buffer.length * 4];
	for (int i = 0; i < buffer.length; i++)
	{
		int j = i * 4;
		int value = buffer[i] & 0xFF;
		bufferi[j] = 255;
		bufferi[j + 1] = 255;
		bufferi[j + 2] = 255;
		bufferi[j + 3] = value;
	}
	int bl = glyph.getBitmapLeft();
	int bt = glyph.getBitmapTop();
	int ax = glyph.getAdvanceX();
```

**Comment by mseleng** [comment]
Thanks for the code. This may sound weird, but it is working now. I guess it didn't work last time, because I had the debugger stopped at some point and was trying to load char in it. Now it works perfectly! Thank you. You can now close this issue.

**Comment by Tinytimrob** [comment]
OK, I'm glad you found this useful 👍
